# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 7.2

steps:
- checkout: self
  persistCredentials: true


- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: |
    cd $(Build.SourcesDirectory)/quickflow
    git config --global user.email "sandeepprasad@eaton.com"
    git config --global user.name "sandeepeat2014"
    
    composer create-project --keep-vcs neos/flow-base-distribution Quickstart
    git add .
    git commit -m "Quickstart added"
    git push

  displayName: 'composer install'
